/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Estudiante
 */
package Interfaz;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import org.armedbear.lisp.Fixnum;
import org.armedbear.lisp.Function;
import org.armedbear.lisp.Interpreter;
import org.armedbear.lisp.Packages;
import org.armedbear.lisp.Package;
import org.armedbear.lisp.Symbol;

public class Plataforma extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    ArrayList<JToggleButton> tabla = new ArrayList<>();
    String dir_player1 = "/imagenes/cruz.png";
    String dir_player2 = "/imagenes/circulo.png";
    URL url_player1 = getClass().getResource(dir_player1);
    ImageIcon icono_player1 = new ImageIcon(url_player1);
    URL url_player2 = getClass().getResource(dir_player2);
    ImageIcon icono_player2 = new ImageIcon(url_player2);
    Color disponible = new Color(153, 153, 255);
    Color no_disponible = new Color(204, 204, 255);
    String dificultad;
    Interpreter interpreter;
    Symbol juegaHumanoSym;
    Symbol juegaMaquinaSym;
    Symbol iniciaSym;
    Symbol estadoSym;
    Function juegaHumanoFun;
    Function juegaMaquinaFun;
    Function iniciaFun;
    Function estadoFun;

    public Plataforma(String dificultad, String jugador1, String jugador2) {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("4 RAYA CON GRAVEDAD");
        this.dificultad = dificultad;
        this.jldificultad.setText(dificultad);
        this.jlJugador.setText(jugador1);
        this.jlPC.setText(jugador2);
        this.jlTurno.setText(jugador1);
        carga_lisp();
        Obtener_Componentes();
        Eventos_Juego();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpTabla = new javax.swing.JPanel();
        jtCuadro = new javax.swing.JToggleButton();
        jtCuadro1 = new javax.swing.JToggleButton();
        jtCuadro2 = new javax.swing.JToggleButton();
        jtCuadro3 = new javax.swing.JToggleButton();
        jtCuadro4 = new javax.swing.JToggleButton();
        jtCuadro5 = new javax.swing.JToggleButton();
        jtCuadro6 = new javax.swing.JToggleButton();
        jtCuadro7 = new javax.swing.JToggleButton();
        jtCuadro8 = new javax.swing.JToggleButton();
        jtCuadro9 = new javax.swing.JToggleButton();
        jtCuadro10 = new javax.swing.JToggleButton();
        jtCuadro11 = new javax.swing.JToggleButton();
        jtCuadro12 = new javax.swing.JToggleButton();
        jtCuadro13 = new javax.swing.JToggleButton();
        jtCuadro14 = new javax.swing.JToggleButton();
        jtCuadro15 = new javax.swing.JToggleButton();
        jtCuadro16 = new javax.swing.JToggleButton();
        jtCuadro17 = new javax.swing.JToggleButton();
        jtCuadro18 = new javax.swing.JToggleButton();
        jtCuadro19 = new javax.swing.JToggleButton();
        jtCuadro20 = new javax.swing.JToggleButton();
        jtCuadro21 = new javax.swing.JToggleButton();
        jtCuadro22 = new javax.swing.JToggleButton();
        jtCuadro23 = new javax.swing.JToggleButton();
        jtCuadro24 = new javax.swing.JToggleButton();
        jtCuadro25 = new javax.swing.JToggleButton();
        jtCuadro26 = new javax.swing.JToggleButton();
        jtCuadro27 = new javax.swing.JToggleButton();
        jtCuadro28 = new javax.swing.JToggleButton();
        jtCuadro29 = new javax.swing.JToggleButton();
        jtCuadro30 = new javax.swing.JToggleButton();
        jtCuadro31 = new javax.swing.JToggleButton();
        jtCuadro32 = new javax.swing.JToggleButton();
        jtCuadro33 = new javax.swing.JToggleButton();
        jtCuadro34 = new javax.swing.JToggleButton();
        jtCuadro35 = new javax.swing.JToggleButton();
        jpTurno = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlTurno = new javax.swing.JLabel();
        jpJugadores = new javax.swing.JPanel();
        jlJugador = new javax.swing.JLabel();
        jlPC = new javax.swing.JLabel();
        imgPC = new javax.swing.JLabel();
        imgPlayer = new javax.swing.JLabel();
        jpNivel = new javax.swing.JPanel();
        jldificultad = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbMenu = new javax.swing.JButton();
        jbNuevaPartida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 520));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jpTabla.setBackground(new java.awt.Color(0, 0, 0));
        jpTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        jtCuadro.setBackground(new java.awt.Color(153, 153, 255));
        jtCuadro.setText(" ");
        jtCuadro.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro1.setBackground(new java.awt.Color(153, 153, 255));
        jtCuadro1.setText(" ");
        jtCuadro1.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro2.setBackground(new java.awt.Color(153, 153, 255));
        jtCuadro2.setText(" ");
        jtCuadro2.setMaximumSize(new java.awt.Dimension(60, 60));
        jtCuadro2.setMinimumSize(new java.awt.Dimension(60, 60));
        jtCuadro2.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro3.setBackground(new java.awt.Color(153, 153, 255));
        jtCuadro3.setText(" ");
        jtCuadro3.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro4.setBackground(new java.awt.Color(153, 153, 255));
        jtCuadro4.setText(" ");
        jtCuadro4.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro5.setBackground(new java.awt.Color(153, 153, 255));
        jtCuadro5.setText(" ");
        jtCuadro5.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro6.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro6.setText(" ");
        jtCuadro6.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro7.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro7.setText(" ");
        jtCuadro7.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro8.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro8.setText(" ");
        jtCuadro8.setMaximumSize(new java.awt.Dimension(60, 60));
        jtCuadro8.setMinimumSize(new java.awt.Dimension(60, 60));
        jtCuadro8.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro9.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro9.setText(" ");
        jtCuadro9.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro10.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro10.setText(" ");
        jtCuadro10.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro11.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro11.setText(" ");
        jtCuadro11.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro12.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro12.setText(" ");
        jtCuadro12.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro13.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro13.setText(" ");
        jtCuadro13.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro14.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro14.setText(" ");
        jtCuadro14.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro15.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro15.setText(" ");
        jtCuadro15.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro16.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro16.setText(" ");
        jtCuadro16.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro17.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro17.setText(" ");
        jtCuadro17.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro18.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro18.setText(" ");
        jtCuadro18.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro19.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro19.setText(" ");
        jtCuadro19.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro20.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro20.setText(" ");
        jtCuadro20.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro21.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro21.setText(" ");
        jtCuadro21.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro22.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro22.setText(" ");
        jtCuadro22.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro23.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro23.setText(" ");
        jtCuadro23.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro24.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro24.setText(" ");
        jtCuadro24.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro25.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro25.setText(" ");
        jtCuadro25.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro26.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro26.setText(" ");
        jtCuadro26.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro27.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro27.setText(" ");
        jtCuadro27.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro28.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro28.setText(" ");
        jtCuadro28.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro29.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro29.setText(" ");
        jtCuadro29.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro30.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro30.setText(" ");
        jtCuadro30.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro31.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro31.setText(" ");
        jtCuadro31.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro32.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro32.setText(" ");
        jtCuadro32.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro33.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro33.setText(" ");
        jtCuadro33.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro34.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro34.setText(" ");
        jtCuadro34.setPreferredSize(new java.awt.Dimension(60, 60));

        jtCuadro35.setBackground(new java.awt.Color(204, 204, 255));
        jtCuadro35.setText(" ");
        jtCuadro35.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jpTablaLayout = new javax.swing.GroupLayout(jpTabla);
        jpTabla.setLayout(jpTablaLayout);
        jpTablaLayout.setHorizontalGroup(
            jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTablaLayout.createSequentialGroup()
                        .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtCuadro6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCuadro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpTablaLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jtCuadro7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTablaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCuadro1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtCuadro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtCuadro8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpTablaLayout.createSequentialGroup()
                                .addComponent(jtCuadro9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCuadro10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCuadro11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTablaLayout.createSequentialGroup()
                                .addComponent(jtCuadro3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCuadro4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCuadro5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jpTablaLayout.createSequentialGroup()
                            .addComponent(jtCuadro18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtCuadro19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtCuadro20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtCuadro21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtCuadro22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtCuadro23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpTablaLayout.createSequentialGroup()
                            .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jpTablaLayout.createSequentialGroup()
                                    .addComponent(jtCuadro30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtCuadro31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtCuadro32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpTablaLayout.createSequentialGroup()
                                    .addComponent(jtCuadro24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtCuadro25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtCuadro26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(5, 5, 5)
                            .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jpTablaLayout.createSequentialGroup()
                                    .addComponent(jtCuadro27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtCuadro28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtCuadro29, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpTablaLayout.createSequentialGroup()
                                    .addComponent(jtCuadro33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtCuadro34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtCuadro35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jpTablaLayout.createSequentialGroup()
                        .addComponent(jtCuadro12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCuadro13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCuadro14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCuadro15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCuadro16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCuadro17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTablaLayout.setVerticalGroup(
            jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTablaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCuadro32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCuadro26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro29, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCuadro23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCuadro17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCuadro6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCuadro11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtCuadro1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtCuadro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtCuadro3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtCuadro4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtCuadro5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtCuadro2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jpTurno.setBackground(new java.awt.Color(153, 153, 255));
        jpTurno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TURNO:");

        jlTurno.setBackground(new java.awt.Color(102, 255, 102));
        jlTurno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlTurno.setForeground(new java.awt.Color(0, 51, 255));
        jlTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpTurnoLayout = new javax.swing.GroupLayout(jpTurno);
        jpTurno.setLayout(jpTurnoLayout);
        jpTurnoLayout.setHorizontalGroup(
            jpTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTurnoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jlTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpTurnoLayout.setVerticalGroup(
            jpTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jlTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpJugadores.setBackground(new java.awt.Color(153, 153, 255));
        jpJugadores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlJugador.setBackground(new java.awt.Color(102, 255, 102));
        jlJugador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlJugador.setForeground(new java.awt.Color(0, 51, 255));
        jlJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlJugador.setText("jugador 1:");

        jlPC.setBackground(new java.awt.Color(102, 255, 102));
        jlPC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlPC.setForeground(new java.awt.Color(0, 51, 255));
        jlPC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPC.setText("ordenador:");

        imgPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo.png"))); // NOI18N

        imgPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruz.png"))); // NOI18N

        javax.swing.GroupLayout jpJugadoresLayout = new javax.swing.GroupLayout(jpJugadores);
        jpJugadores.setLayout(jpJugadoresLayout);
        jpJugadoresLayout.setHorizontalGroup(
            jpJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpJugadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpJugadoresLayout.createSequentialGroup()
                        .addComponent(jlJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpJugadoresLayout.createSequentialGroup()
                        .addComponent(jlPC, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgPC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jpJugadoresLayout.setVerticalGroup(
            jpJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpJugadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imgPC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpJugadoresLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlPC)
                .addGap(19, 19, 19))
        );

        jpNivel.setBackground(new java.awt.Color(153, 153, 255));
        jpNivel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jldificultad.setBackground(new java.awt.Color(102, 255, 102));
        jldificultad.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jldificultad.setForeground(new java.awt.Color(51, 51, 255));
        jldificultad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DIFICULTAD:");

        javax.swing.GroupLayout jpNivelLayout = new javax.swing.GroupLayout(jpNivel);
        jpNivel.setLayout(jpNivelLayout);
        jpNivelLayout.setHorizontalGroup(
            jpNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
            .addComponent(jldificultad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpNivelLayout.setVerticalGroup(
            jpNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNivelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jldificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jbMenu.setBackground(new java.awt.Color(153, 153, 255));
        jbMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbMenu.setText("MENU INICIO");
        jbMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbMenuMouseExited(evt);
            }
        });

        jbNuevaPartida.setBackground(new java.awt.Color(153, 153, 255));
        jbNuevaPartida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbNuevaPartida.setText("NUEVA PARTIDA");
        jbNuevaPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbNuevaPartidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbNuevaPartidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbNuevaPartidaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 411, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpJugadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpNivel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbNuevaPartida, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jpNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jpJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jbNuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jpTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNuevaPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNuevaPartidaMouseClicked
        /*  Si es que se selecciona Nueva Partida,
            procedemos a limpiar el tablero
            e iniciamos una nueva partida con la misma dificultad elegida
         */
        for (int i = 0; i < 36; i++) {
            tabla.get(i).setIcon(null);
            tabla.get(i).setEnabled(true);
            if (i > 5) {
                tabla.get(i).setBackground(no_disponible);
            }
        }
        switch (dificultad) {
            case "FACIL":
                iniciaFun.execute(Fixnum.getInstance(1), Fixnum.getInstance(1));
                break;
            case "INTERMEDIO":
                iniciaFun.execute(Fixnum.getInstance(1), Fixnum.getInstance(2));
                break;
            case "DIFICIL":
                iniciaFun.execute(Fixnum.getInstance(1), Fixnum.getInstance(3));
        }

    }//GEN-LAST:event_jbNuevaPartidaMouseClicked

    private void jbMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMenuMouseClicked
        // regresamos a la pantalla de configuración
        new Menu_Inicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbMenuMouseClicked

    private void jbNuevaPartidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNuevaPartidaMouseEntered
        // TODO add your handling code here:
        jbNuevaPartida.setSize(217, 54);
    }//GEN-LAST:event_jbNuevaPartidaMouseEntered

    private void jbNuevaPartidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNuevaPartidaMouseExited
        // TODO add your handling code here:
        jbNuevaPartida.setSize(213, 50);
    }//GEN-LAST:event_jbNuevaPartidaMouseExited

    private void jbMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMenuMouseEntered
        // TODO add your handling code here:
        jbMenu.setSize(217, 54);
    }//GEN-LAST:event_jbMenuMouseEntered

    private void jbMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMenuMouseExited
        // TODO add your handling code here:
        jbMenu.setSize(213, 50);
    }//GEN-LAST:event_jbMenuMouseExited
    private void CuadroMouseClicked(java.awt.event.MouseEvent evt) throws InterruptedException {
        // Se busca de donde provino el evento en el tablero
        JToggleButton temp = (JToggleButton) evt.getSource();
        if (temp.getIcon() == null) {
            juega((JToggleButton) evt.getSource());
        }else{
            evt.consume();
        }
    }

    private void Eventos_Juego() // agregamos los eventos a cada una de las posiciones en el tablero
    {
        for (int i = 0; i <= 35; i++) {
            tabla.get(i).addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    try {
                        CuadroMouseClicked(evt);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Plataforma.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
        }
    }

    private void juega(JToggleButton boton) throws InterruptedException {   // llamamos al metodo jugar si el lugar seleccionado esta disponible
        float[] disponible2 = {153, 153, 255};
        disponible2 = boton.getBackground().getColorComponents(disponible2);
        if (disponible2[0] == (float) 0.6 && disponible2[1] == (float) 0.6 && disponible2[2] == (float) 1.0) {
            int i = 0;
            while (i <= 35) {
                if (tabla.get(i) != boton) {
                    i++;
                } else {
                    Jugar(jlTurno.getText(), i);
                    i = 36;
                }
            }
        }
    }

    //llamar a jugada computador
    private void Jugar(String jugador, int pos) throws InterruptedException {
        if (jlJugador.getText().equals(jugador)) {

            tabla.get(pos).setIcon(icono_player1); // Actualizamos el tablero con la jugada del humano
            int temp = pos % 6; // Se obtiene la columna donde jugó el humano

            //Actualizamos el tablero en lisp con la jugada del humano
            juegaHumanoFun.execute(Fixnum.getInstance(temp));

            /* Se llama a la funcion de lisp
                que nos devuelve el estado actual del juego
                1 = Ganó el humano
               -1 = Ganó la maquina
                0 = Sigue el juego
             */
            int estado = estadoFun.execute().intValue();

            //Se comprueba si ganó el humano
            if (estado == 1) {
                JOptionPane.showMessageDialog(this, "HAS GANADO!");
                disableAll(); //esto desactiva todos los botones, hay que modificar

                // Se sigue jugando en caso contrario
            } else {
                if (pos + 6 <= 35) {
                    tabla.get(pos + 6).setBackground(disponible);
                }
                jlTurno.setText(jlPC.getText());
                JugadaComputador();
            }

        } else {
            tabla.get(pos).setIcon(icono_player2); // Actualizamos el tablero con la jugada de la maquina

            /* Se llama a la funcion de lisp
                que nos devuelve el estado actual del juego
                1 = Ganó el humano
               -1 = Ganó la maquina
                0 = Sigue el juego
             */
            int estado = estadoFun.execute().intValue();

            // Se comprueba si ganó la máquina
            if (estado == -1) {
                JOptionPane.showMessageDialog(this, "HAS PERDIDO!");
                disableAll(); //esto desactiva todos los botones, hay que modificar
            }
            if (pos + 6 <= 35) {
                tabla.get(pos + 6).setBackground(disponible);
            }
            jlTurno.setText(jlJugador.getText());
        }
    }

    private void JugadaComputador() throws InterruptedException {
        /* Obtendra la jugada de la maquina
            a partir del codigo lisp
            dependiendo de la dificultad que se eligio
         */
        int pos = juegaMaquinaFun.execute().intValue(); //Determinar jugada de computador
        //System.out.println(pos);
        Jugar("ordenador", pos);
    }

    private void Obtener_Componentes() {
        tabla.add(jtCuadro);
        tabla.add(jtCuadro1);
        tabla.add(jtCuadro2);
        tabla.add(jtCuadro3);
        tabla.add(jtCuadro4);
        tabla.add(jtCuadro5);
        tabla.add(jtCuadro6);
        tabla.add(jtCuadro7);
        tabla.add(jtCuadro8);
        tabla.add(jtCuadro9);
        tabla.add(jtCuadro10);
        tabla.add(jtCuadro11);
        tabla.add(jtCuadro12);
        tabla.add(jtCuadro13);
        tabla.add(jtCuadro14);
        tabla.add(jtCuadro15);
        tabla.add(jtCuadro16);
        tabla.add(jtCuadro17);
        tabla.add(jtCuadro18);
        tabla.add(jtCuadro19);
        tabla.add(jtCuadro20);
        tabla.add(jtCuadro21);
        tabla.add(jtCuadro22);
        tabla.add(jtCuadro23);
        tabla.add(jtCuadro24);
        tabla.add(jtCuadro25);
        tabla.add(jtCuadro26);
        tabla.add(jtCuadro27);
        tabla.add(jtCuadro28);
        tabla.add(jtCuadro29);
        tabla.add(jtCuadro30);
        tabla.add(jtCuadro31);
        tabla.add(jtCuadro32);
        tabla.add(jtCuadro33);
        tabla.add(jtCuadro34);
        tabla.add(jtCuadro35);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgPC;
    private javax.swing.JLabel imgPlayer;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbMenu;
    private javax.swing.JButton jbNuevaPartida;
    private javax.swing.JLabel jlJugador;
    private javax.swing.JLabel jlPC;
    private javax.swing.JLabel jlTurno;
    private javax.swing.JLabel jldificultad;
    private javax.swing.JPanel jpJugadores;
    private javax.swing.JPanel jpNivel;
    private javax.swing.JPanel jpTabla;
    private javax.swing.JPanel jpTurno;
    private javax.swing.JToggleButton jtCuadro;
    private javax.swing.JToggleButton jtCuadro1;
    private javax.swing.JToggleButton jtCuadro10;
    private javax.swing.JToggleButton jtCuadro11;
    private javax.swing.JToggleButton jtCuadro12;
    private javax.swing.JToggleButton jtCuadro13;
    private javax.swing.JToggleButton jtCuadro14;
    private javax.swing.JToggleButton jtCuadro15;
    private javax.swing.JToggleButton jtCuadro16;
    private javax.swing.JToggleButton jtCuadro17;
    private javax.swing.JToggleButton jtCuadro18;
    private javax.swing.JToggleButton jtCuadro19;
    private javax.swing.JToggleButton jtCuadro2;
    private javax.swing.JToggleButton jtCuadro20;
    private javax.swing.JToggleButton jtCuadro21;
    private javax.swing.JToggleButton jtCuadro22;
    private javax.swing.JToggleButton jtCuadro23;
    private javax.swing.JToggleButton jtCuadro24;
    private javax.swing.JToggleButton jtCuadro25;
    private javax.swing.JToggleButton jtCuadro26;
    private javax.swing.JToggleButton jtCuadro27;
    private javax.swing.JToggleButton jtCuadro28;
    private javax.swing.JToggleButton jtCuadro29;
    private javax.swing.JToggleButton jtCuadro3;
    private javax.swing.JToggleButton jtCuadro30;
    private javax.swing.JToggleButton jtCuadro31;
    private javax.swing.JToggleButton jtCuadro32;
    private javax.swing.JToggleButton jtCuadro33;
    private javax.swing.JToggleButton jtCuadro34;
    private javax.swing.JToggleButton jtCuadro35;
    private javax.swing.JToggleButton jtCuadro4;
    private javax.swing.JToggleButton jtCuadro5;
    private javax.swing.JToggleButton jtCuadro6;
    private javax.swing.JToggleButton jtCuadro7;
    private javax.swing.JToggleButton jtCuadro8;
    private javax.swing.JToggleButton jtCuadro9;
    // End of variables declaration//GEN-END:variables

    private void carga_lisp() {

        //Creamos el objeto que hara la conexion entre Java y Lisp
        interpreter = Interpreter.createInstance();
        interpreter.eval("(load \"proyecto_lisp_java\")");

        //Usaremos el package predeterminado en lisp
        Package defaultPackage = Packages.findPackage("CL-USER");

        // Se busca en el package definido las funciones indicadas en el parametro
        juegaHumanoSym = defaultPackage.findAccessibleSymbol("JUEGA-HUMANO");
        juegaMaquinaSym = defaultPackage.findAccessibleSymbol("JUEGA-MAQUINA");
        iniciaSym = defaultPackage.findAccessibleSymbol("INICIA-JUEGO");
        estadoSym = defaultPackage.findAccessibleSymbol("GETESTADO");

        // Obtenemos la "funcion" a partir de su nombre (del paso anterior)
        juegaHumanoFun = (Function) juegaHumanoSym.getSymbolFunction();
        juegaMaquinaFun = (Function) juegaMaquinaSym.getSymbolFunction();
        iniciaFun = (Function) iniciaSym.getSymbolFunction();
        estadoFun = (Function) estadoSym.getSymbolFunction();

        // Se ejecuta la funcion que inicia el juego en lisp
        // Con su respectiva dificultad
        switch (dificultad) {
            case "FACIL":
                iniciaFun.execute(Fixnum.getInstance(1), Fixnum.getInstance(1));
                break;
            case "INTERMEDIO":
                iniciaFun.execute(Fixnum.getInstance(1), Fixnum.getInstance(2));
                break;
            case "DIFICIL":
                iniciaFun.execute(Fixnum.getInstance(1), Fixnum.getInstance(3));
        }
    }

    private void disableAll() {
        for (JToggleButton j : tabla) {
            j.setEnabled(false);
        }
    }
}
